
// import { Inter } from "next/font/google";
// // import "./globals.css";
// import Sidebar from "@/components/sidebar";
// import Chat from '@/components/chat'
// import StoreProvider from "../storeProvider/storeProvider";
// import { AppProvider } from "@/context/socket";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next Apptt",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children}) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>


    
    
//    <StoreProvider>
   
//     <main className="  flex h-screen">
        
//         <Sidebar />
//         {/* <Chat /> */}
//         {children}
      
//         </main>

 
//    </StoreProvider>
   
   

     

      

//       </body>
//     </html>
//   );
// }




import { Inter } from "next/font/google";
import StoreProvider from "@/storeProvider/storeProvider";
import CallLayout from "@/components/callLayout";
import OutgoingCallLayout from "@/components/outgoingCallLayout";

// import "../globals.css";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <body className={inter.className}>
        <StoreProvider>
       
          <OutgoingCallLayout />
   
     
              {/* <CallLayout /> */}
             
       
       
        {children}
        </StoreProvider>
        
      </body>
  
  );
}
