import { Inter } from "next/font/google";
import Chat from "@/components/chat";
import '@/app/globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WhispTalk | Messages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <div className=" flex">
        <Chat />
        {children}
      </div>


 
  );
}
